[package]
name = "apibara-client-protos"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.8.0"
prost = "0.11.0"
prost-types = "0.11.1"
num-bigint = "0.4.3"
hex = "0.4.3"

[build-dependencies]
tonic-build = "0.8.0"
